### ISSUE TITLE
Comparing the names of programs to those described in Enterobase docs

### ISSUE THREAD

**Issue by nickp60** [zheminzhou/EToKi#7]
Hi @zheminzhou ,

 am trying to recreate the SNP analysis that would be performed on EnteroBase, given a directory of assemblies.

Would it be possible to add a note to the README about what programs correspond to the [steps listed in the EnteroBase docs](https://enterobase.readthedocs.io/en/latest/pipelines/enterobase-pipelines.html#snp-trees)?   

For what I can tell, it seems like:

- `refMasker`  ~  `RecHMM`
- `refMapper `  ~ `align`
- `refMapper_matrix`  ~ `RecFilter`
- `matrix_phylogeny ` ~ `phylo`

... but if that's the case, I'm not sure where the SNP matrix required by `RecHMM` would come from; the docs describe `refMasker` as identifying recombination regions from a reference genome, while `RecHMM` identifies regions from a SNP matrix.

 Any help would be appreciated!

Thanks,

~Nick

**Comment by zheminzhou** [comment]
RefMasker is a module that masks repetitive regions in the reference genome, rather than recombinant regions. The RecHMM and RecFilter modules are designed to do similar things as "Gubbins" and "ClonalFrame". They are somewhat unrelated to what you want. 

In EnteroBase, we separate RefMasker, RefMapper and RefMapper_matrix as individual procedures, because we want to save intemediate files, which can be reused later. 

Here as a standalone version package 'EToKi', the three steps in EnteroBase are concatenated together into "EToKi align". You do not need to run them separately (although you can still do that). 

For your use, you can just run EToKi align, and put reference and queried genomes in, "EToKi align" will (1) mask the reference, (2) align queried genomes into reference, and (3) generate the SNP matrix. 

The output of EToKi align can then be fed into "EToKi phylo" to get the ML tree.

**Comment by nickp60** [comment]
Thanks so much!
